const translations = {
  en: {
    navbar: {
      home: 'Home',
      preapproval: 'Pre-approval',
      inventory: 'Inventory',
      menu: 'Menu',
    },
    languageOptions: {
      en: 'English',
      es: 'Spanish',
    },
    preapproval: {
      title: 'Get Pre-Approved',
      steps: {
        personal: 'Personal',
        residence: 'Residence',
        employment: 'Employment',
        vehicle: 'Vehicle',
      },
      stepTitles: {
        1: 'Step 1: Personal Information',
        2: 'Step 2: Current Residence',
        3: 'Step 3: Employment & Income',
        4: 'Step 4: Vehicle Interest',
      },
      labels: {
        firstName: 'First Name *',
        middleName: 'Middle Name',
        lastName: 'Last Name *',
        email: 'Email',
        phone: 'Phone *',
        dob: 'Date of Birth *',
        socialOrItin: 'Social Security Number or ITIN *',
        licenseNumber: "Driver's License Number *",
        licenseState: "Driver's License State *",
        address: 'Street Address *',
        state: 'State *',
        city: 'City *',
        zip: 'Zip Code *',
        timeAtAddress: 'Time at Address *',
        housing: 'Housing',
        employmentType: 'Employment Type *',
        companyName: 'Company Name *',
        occupation: 'Occupation *',
        income: 'Monthly Income *',
        additionalIncome: 'Additional Income',
        timeAtJob: 'Time at Job *',
        carType: 'Vehicle of Interest',
        downPayment: 'Estimated Down Payment',
      },
      placeholders: {
        socialOrItin: 'XXX-XX-XXXX or ITIN',
        timeAtAddress: 'e.g., 2 years',
        timeAtJob: 'e.g., 1 year',
      },
      options: {
        employmentType: {
          select: 'Select employment type',
          selfEmployed: 'Self employed',
          fullTime: 'Employed full time',
          partTime: 'Employed part time',
          other: 'Other',
        },
        state: {
          loading: 'Loading states...',
          select: 'Select a state',
        },
        city: {
          loading: 'Loading cities...',
          select: 'Select a city',
        },
      },
      errors: {
        required: 'This field is required',
        email: 'Invalid email format',
        phone: 'Phone must be at least 10 digits',
        income: 'Income must be greater than 0',
        dob: 'You must be at least 18 years old',
        nameLetters: 'Name must contain only letters and spaces',
        numberDigits: 'Number must contain only digits',
        dateFuture: 'Date must be today or in the future',
      },
      buttons: {
        back: '← Back',
        next: 'Next →',
        submit: 'Submit Application',
        submitting: 'Submitting...',
      },
      alerts: {
        missingInfo: 'Missing or invalid information',
        completeFields: 'Please complete all required fields correctly before continuing.',
        success: 'Application Submitted',
        successText: 'A Motor Vibes specialist will contact you shortly.',
        error: 'Error',
        errorText: 'Something went wrong. Please try again.',
        apiError: 'Failed to load states. Please try again.',
        apiErrorCities: 'Failed to load cities. Please try again.',
      },
    },
    contact: {
      title: 'Schedule a test drive',
      labels: {
        name: 'Name:',
        number: 'Number:',
        email: 'Email:',
        date: 'Date:',
      },
      placeholders: {
        name: 'Put your name here',
        number: 'Put your number here',
        email: 'Put your email here',
      },
      buttons: {
        submit: 'Schedule Your Test Drive',
        sending: 'Sending...',
      },
      alerts: {
        missingInfo: 'Missing or invalid information',
        correctErrors: 'Please correct the errors before submitting.',
        success: 'Reservation Submitted',
        successText: 'Thank you! We will contact you soon to confirm your test drive.',
        error: 'Error',
        errorText: 'Something went wrong. Please try again.',
        sendError: 'Failed to send. Please check your connection.',
      },
    },
  },
  es: {
    navbar: {
      home: 'Inicio',
      preapproval: 'Pre-aprobación',
      inventory: 'Inventario',
      menu: 'Menú',
    },
    languageOptions: {
      en: 'Inglés',
      es: 'Español',
    },
    preapproval: {
      title: 'Obtener Pre-Aprobación',
      steps: {
        personal: 'Personal',
        residence: 'Residencia',
        employment: 'Empleo',
        vehicle: 'Vehículo',
      },
      stepTitles: {
        1: 'Paso 1: Información Personal',
        2: 'Paso 2: Residencia Actual',
        3: 'Paso 3: Empleo e Ingresos',
        4: 'Paso 4: Interés en Vehículo',
      },
      labels: {
        firstName: 'Nombre *',
        middleName: 'Segundo Nombre',
        lastName: 'Apellido *',
        email: 'Correo Electrónico',
        phone: 'Teléfono *',
        dob: 'Fecha de Nacimiento *',
        socialOrItin: 'Número de Seguro Social o ITIN *',
        licenseNumber: 'Número de Licencia de Conducir *',
        licenseState: 'Estado de Licencia de Conducir *',
        address: 'Dirección de Calle *',
        state: 'Estado *',
        city: 'Ciudad *',
        zip: 'Código Postal *',
        timeAtAddress: 'Tiempo en la Dirección *',
        housing: 'Vivienda',
        employmentType: 'Tipo de Empleo *',
        companyName: 'Nombre de la Empresa *',
        occupation: 'Ocupación *',
        income: 'Ingreso Mensual *',
        additionalIncome: 'Ingreso Adicional',
        timeAtJob: 'Tiempo en el Trabajo *',
        carType: 'Vehículo de Interés',
        downPayment: 'Pago Inicial Estimado',
      },
      placeholders: {
        socialOrItin: 'XXX-XX-XXXX o ITIN',
        timeAtAddress: 'ej., 2 años',
        timeAtJob: 'ej., 1 año',
      },
      options: {
        employmentType: {
          select: 'Seleccionar tipo de empleo',
          selfEmployed: 'Autónomo',
          fullTime: 'Empleado a tiempo completo',
          partTime: 'Empleado a tiempo parcial',
          other: 'Otro',
        },
        state: {
          loading: 'Cargando estados...',
          select: 'Seleccionar un estado',
        },
        city: {
          loading: 'Cargando ciudades...',
          select: 'Seleccionar una ciudad',
        },
      },
      errors: {
        required: 'Este campo es obligatorio',
        email: 'Formato de correo electrónico inválido',
        phone: 'El teléfono debe tener al menos 10 dígitos',
        income: 'El ingreso debe ser mayor a 0',
        dob: 'Debes tener al menos 18 años',
        nameLetters: 'El nombre debe contener solo letras y espacios',
        numberDigits: 'El número debe contener solo dígitos',
        dateFuture: 'La fecha debe ser hoy o en el futuro',
      },
      buttons: {
        back: '← Atrás',
        next: 'Siguiente →',
        submit: 'Enviar Solicitud',
        submitting: 'Enviando...',
      },
      alerts: {
        missingInfo: 'Información faltante o inválida',
        completeFields: 'Por favor, complete todos los campos requeridos correctamente antes de continuar.',
        success: 'Solicitud Enviada',
        successText: 'Un especialista de Motor Vibes se pondrá en contacto contigo pronto.',
        error: 'Error',
        errorText: 'Algo salió mal. Por favor, inténtalo de nuevo.',
        apiError: 'Error al cargar estados. Por favor, inténtalo de nuevo.',
        apiErrorCities: 'Error al cargar ciudades. Por favor, inténtalo de nuevo.',
      },
    },
    contact: {
      title: 'Programa una prueba de manejo',
      labels: {
        name: 'Nombre:',
        number: 'Número:',
        email: 'Correo Electrónico:',
        date: 'Fecha:',
      },
      placeholders: {
        name: 'Pon tu nombre aquí',
        number: 'Pon tu número aquí',
        email: 'Pon tu correo electrónico aquí',
      },
      buttons: {
        submit: 'Programa Tu Prueba de Manejo',
        sending: 'Enviando...',
      },
      alerts: {
        missingInfo: 'Información faltante o inválida',
        correctErrors: 'Por favor, corrige los errores antes de enviar.',
        success: 'Reserva Enviada',
        successText: '¡Gracias! Nos pondremos en contacto contigo pronto para confirmar tu prueba de manejo.',
        error: 'Error',
        errorText: 'Algo salió mal. Por favor, inténtalo de nuevo.',
        sendError: 'Error al enviar. Por favor, verifica tu conexión.',
      },
    },
  },
};

export default translations;